"""initial tables

Revision ID: 984022f46648
Revises: 
Create Date: 2026-04-07 11:05:27.523147

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '984022f46648'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_destino', sa.Integer(), nullable=False),
    sa.Column('tipo_destino', sa.Enum('responsavel', 'co_responsavel', 'filho', name='tipodestinonotificacao'), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('corpo', sa.String(length=500), nullable=False),
    sa.Column('tipo_evento', sa.Enum('tarefa_enviada', 'tarefa_aprovada', 'tarefa_rejeitada', 'tarefa_expirada', 'resgate_solicitado', 'resgate_entregue', 'nivel_subiu', 'item_destravado', name='tipoeventonotificacao'), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('lida', sa.Integer(), nullable=True),
    sa.Column('enviada_push', sa.Integer(), nullable=True),
    sa.Column('criada_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('lida_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('max_filhos', sa.Integer(), nullable=False),
    sa.Column('max_tarefas_ativas', sa.Integer(), nullable=False),
    sa.Column('permite_foto', sa.Integer(), nullable=True),
    sa.Column('permite_co_resp', sa.Integer(), nullable=True),
    sa.Column('permite_relatorios', sa.Integer(), nullable=True),
    sa.Column('preco_mensal', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('preco_anual', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('familias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_familia', sa.String(length=100), nullable=False),
    sa.Column('email_responsavel', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('id_plano', sa.Integer(), nullable=False),
    sa.Column('modo_progressao', sa.Integer(), nullable=True),
    sa.Column('percentual_multa_padrao', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('gateway_customer_id', sa.String(length=100), nullable=True),
    sa.Column('trial_expira_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_plano'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_responsavel')
    )
    op.create_table('consentimentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_familia', sa.Integer(), nullable=False),
    sa.Column('versao_termo', sa.String(length=20), nullable=False),
    sa.Column('ip_origem', sa.String(length=45), nullable=False),
    sa.Column('aceito_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_familia'], ['familias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('familia_membros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_familia', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('pode_criar_tarefas', sa.Integer(), nullable=True),
    sa.Column('pode_aprovar', sa.Integer(), nullable=True),
    sa.Column('pode_gerenciar_loja', sa.Integer(), nullable=True),
    sa.Column('pode_ver_relatorios', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_familia'], ['familias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('filhos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_familia', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('pontos_saldo', sa.Integer(), nullable=True),
    sa.Column('xp_total', sa.Integer(), nullable=True),
    sa.Column('nivel_atual', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_familia'], ['familias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loja_produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_familia', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('preco_pontos', sa.Integer(), nullable=False),
    sa.Column('nivel_minimo_xp', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('fisico', 'tempo', 'experiencia', name='tipoproduto'), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('exibir_esgotado', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Integer(), nullable=True),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_familia'], ['familias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qrcodes_acesso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_filho', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_filho'], ['filhos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('resgates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_filho', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('preco_pontos_pago', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'entregue', 'cancelado', name='statusresgate'), nullable=True),
    sa.Column('id_confirmador', sa.Integer(), nullable=True),
    sa.Column('data_resgate', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_entrega', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_filho'], ['filhos.id'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['loja_produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarefas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_filho', sa.Integer(), nullable=False),
    sa.Column('id_criador', sa.Integer(), nullable=False),
    sa.Column('tipo_criador', sa.Enum('responsavel', 'co_responsavel', name='tipocriador'), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('pontos_recompensa', sa.Integer(), nullable=False),
    sa.Column('xp_recompensa', sa.Integer(), nullable=False),
    sa.Column('data_limite', sa.DateTime(), nullable=False),
    sa.Column('data_envio_foto', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('foto_obrigatoria', sa.Integer(), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'em_analise', 'concluida', 'rejeitada', 'expirada', 'cancelada', name='statustarefa'), nullable=True),
    sa.Column('motivo_rejeicao', sa.String(length=500), nullable=True),
    sa.Column('percentual_multa_aplicado', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_filho'], ['filhos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacoes_pontos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_filho', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('tarefa', 'compra', 'multa', 'ajuste_manual', 'estorno', name='tipotransacaopontos'), nullable=False),
    sa.Column('ref_tabela', sa.Enum('tarefas', 'resgates', 'manual', name='reftabelapontos'), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_filho'], ['filhos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacoes_xp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_filho', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('tarefa', 'multa', 'ajuste_manual', name='tipotransacaoxp'), nullable=False),
    sa.Column('ref_tabela', sa.Enum('tarefas', 'manual', name='reftabelaxp'), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('nivel_antes', sa.Integer(), nullable=False),
    sa.Column('nivel_depois', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_filho'], ['filhos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacoes_xp')
    op.drop_table('transacoes_pontos')
    op.drop_table('tarefas')
    op.drop_table('resgates')
    op.drop_table('qrcodes_acesso')
    op.drop_table('loja_produtos')
    op.drop_table('filhos')
    op.drop_table('familia_membros')
    op.drop_table('consentimentos')
    op.drop_table('familias')
    op.drop_table('planos')
    op.drop_table('notificacoes')
    op.drop_table('admins')
    # ### end Alembic commands ###
